
// Automaticaly generated by MINIT with RRflex
#import "AppDelegate_iPhone.h"
#import "ATInject.h"

@interface AppDelegate_iPhone ( MINITInjectionHelper )

+(id)class_builder:(id<ATInject>)inject;

@end
       
@implementation AppDelegate_iPhone ( MINITInjectionHelper )

+(id)class_builder:(id<ATInject>)inject{
  NSString * p_0_xibName = [inject instanceOf:[NSString class] named:@"MainWindow"];
  
  return [[[self alloc] initWithXibName: p_0_xibName ] autorelease];
}
      
@end
        